### PR TITLE
Fix: Prevent mowing motor from starting and stopping repeatedly if GPS fix is lost.

### PR DESCRIPTION
**Pull request by olliewalsh**

### CODE REVIEW

**Comment by fallingcats** [comment]
This should be resolved in the latest `releases-edge` build, right? Because I don't think it is, it still does the spin-up thing every couple of seconds.

**Comment by fallingcats** [comment]
> This should be resolved in the latest `releases-edge` build, right? Because I don't think it is, it still does the spin-up thing every couple of seconds.

I retract my earlier statement, I was sure I heard it, but don't think it does the thing anymore. MQTT data seems to confirm that.

**Comment by ClemensElflein** [comment]
thank you for reporting back! I'm glad it's fixed

**Comment by fallingcats** [comment]
Sorry, it still isn't fixed. It just also coincided with another bug where some things apparently aren't updated while "PAUSED". That includes battery % and now motor current apparently. Voltage still updates though.

**Comment by olliewalsh** [comment]
> Sorry, it still isn't fixed. It just also coincided with another bug where some things apparently aren't updated while "PAUSED". That includes battery % and now motor current apparently. Voltage still updates though.

How are you testing? If it's using manual mowing in openmower-gui that will no longer work (it never should have, relied on this bug).
Battery % will not be updated if gps is timing out, will look into fixing that one. I expect you're mistaken about motor current.

**Comment by fallingcats** [comment]
> > Sorry, it still isn't fixed. It just also coincided with another bug where some things apparently aren't updated while "PAUSED". That includes battery % and now motor current apparently. Voltage still updates though.
> 
> How are you testing? If it's using manual mowing in openmower-gui that will no longer work (it never should have, relied on this bug). Battery % will not be updated if gps is timing out, will look into fixing that one. I expect you're mistaken about motor current.

I might have been trying to use manual mowing, but I could hear the motor try to spin up and stop, while not seeing any current  in Home Assistant. I don't know where in the pipe the updates are stuck, but can't see them like I could before

**Pull request merged**
