### PR TITLE
Add basic devcontainer.json

### PR DESCRIPTION
**Pull request by jeremysalwen**

### CODE REVIEW

**Comment by ClemensElflein** [comment]
LGTM, thank you for the PR

**Comment by vermut** [comment]
how do you source catkin env in this setup?

**Comment by jeremysalwen** [comment]
@vermut I just created a PR with the rest of the changes I added to get it working easily: https://github.com/ClemensElflein/open_mower_ros/pull/140

**Comment by vermut** [comment]
Amazing! I tried this but got stuck. But I'm using IntelliJ which seems less versatile.

**Comment by jeremysalwen** [comment]
I'm using vs code, but I don't feel like the dev environment works very well for me, so you might want to try other approaches anyways.

**Pull request merged**
